version: '3.9'
volumes:
  db-store:
services:
    web:
        image: nginx:1.21.6-alpine
        ports:
            - 34251:80
        volumes:
            - ./src:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
    app:
        build: ./docker/php
        volumes:
            - ./src:/var/www
        links:
            - db
        depends_on:
            - db
    db:
        image: mysql:8.0.26
        platform: 'linux/amd64'
        volumes:
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - db-store:/var/lib/mysql
        ports:
            - 2435:3306
        environment:
            MYSQL_DATABASE: sample
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            TZ: "Asia/Tokyo"